### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by simonbrent** [RNAcentral/angularjs-genoverse#16]
The documentation at https://github.com/simonbrent/Genoverse/blob/master/docs/ is not finalized, and is likely to undergo dramatic changes before it appears on https://github.com/wtsi-web/Genoverse.

I am not particularly happy about that fact that you published links to it.

**Comment by BurkovBA** [comment]
Hi, Simon! 

Actually, in my opinion this documentation of your is of very high quality and incredibly helpful, it was really missing.

Do you want me to remove those links? Are there any legal issues or anything?

**Comment by simonbrent** [comment]
The problem with that documentation as is stands is that it is incomplete and [probably] out of date, and I haven't had time to do the work needed to finish it. I generally prefer to get things right, rather than release something that I don't think is ready ;-)

I'm also concerned that linking to my repo will confuse people, who I think would be quite likely to go from the docs to look at the code, which is hugely behind the main repo.

**Comment by simonbrent** [comment]
Re action: yes, please do what you have suggested, thanks.

Re long/short jumps: I do agree to a point, although if you have users who dislike change (i.e., all users!) repeatedly changing an interface over a short period of time would be detrimental to their experience of the product. The real problem I have with the documentation at this point is that Genoverse is basically a side project for me, which I occasionally get to work on as part of my main job, but the time taken to get back into the headspace where I could start writing more docs is practically a long jump by itself! (Also, pretty much all of the work I've been doing recently is impossible to break up into smaller shippable chunks, since it has involved rewriting whole interfaces and all the bits of the interface have to work at the same time).

I will think about publishing the documentation in its current format in the near future, because you're right - thinking about how much more there is to do is stressful enough that I've been ignoring it for almost a year now...

**Comment by BurkovBA** [comment]
Simon, I've added warnings to the documentation page, as we agreed: https://github.com/RNAcentral/angularjs-genoverse/blob/master/README.md. If you'd like them to look any different, tell me or just fork it, change it and send me a PR.

Totally understand what you're saying about part-time, headspace and expensive context switch and no way to break the work into smaller chunks. Maybe then it's worth publishing current docs indeed. Oh, BTW, thank you for getting Genoverse this far.

**Comment by simonbrent** [comment]
Hopefully that'll be fine for now. Thanks.
