### ISSUE TITLE
use my own data (from a local mysql server)?

### ISSUE THREAD

**Issue by evolgeniusteam** [RNAcentral/angularjs-genoverse#17]
thank you for this wonderful too. 

I am new to Genoverse and this might be a dumb question: instead of loading data from Ensembl, is there a way to load my own data from a local MySQL server?

Please kindly provide some example codes.

Thank you very much.

**Comment by BurkovBA** [comment]
@evolgeniusteam 

Hi. 

Yes, you can load data from any url you like. Just pass a function that returns a line like `http://mysite.org/sequence/region/homo_sapiens/__CHR__:__START__-__END__?content-type=text/plain` as `url` parameter for your track like here: https://github.com/RNAcentral/angularjs-genoverse/blob/master/app.js#L340

```
<genoverse genome="genome" chromosome="chromosome" start="start" end="end" example-locations="exampleLocations">
    <genoverse-track name="'Sequence'" model="Genoverse.Track.Model.Sequence.Ensembl" view="Genoverse.Track.View.Sequence" controller="Genoverse.Track.Controller.Sequence" url="urls.sequence" resizable="'auto'" auto-height="true" extra="{100000: false}"></genoverse-track>
    <genoverse-track name="'Genes'" labels="true" info="'Ensembl API genes'" model="Genoverse.Track.Model.Gene.Ensembl" view="Genoverse.Track.View.Gene.Ensembl" url="urls.genes" resizable="'auto'" auto-height="true"></genoverse-track>
    <genoverse-track name="'Transcripts'" labels="true" info="'Ensembl API transcripts'" model="Genoverse.Track.Model.Transcript.Ensembl" view="Genoverse.Track.View.Transcript.Ensembl" url="urls.transcripts" resizable="'auto'" auto-height="true"></genoverse-track>
</genoverse>
```

**Comment by pradyumnasagar** [comment]
how to load bed file as default track? can we add different color in bed file if value is positive/ negative.
Thank you

**Comment by AntonPetrov** [comment]
@pradyumnasagar Thank you for reaching out! According to Genoverse manual:

> Local files can simply be dragged and dropped directly onto Genoverse from the file manager, which will trigger the parsing of the data within the browser, and visualise it as a new track

but I need to check if this functionality works in the angularjs-genoverse implementation. 

Could you please provide more information about what you are trying to do? Are you installing the widget yourself or using it on [rnacentral.org](https://rnacentral.org)?

**Comment by pradyumnasagar** [comment]
> Could you please provide more information about what you are trying to do? Are you installing the widget yourself or using it on [rnacentral.org](https://rnacentral.org)?

I am trying to add a track (without drag-drop. a default track in bam format). The bed file contains the score, how can I make the bed file as a default track and can we change the track color according to the score eg: 
chr1 10000 1100 5
chr1 12000 1400 -5
in the browser track can +5 be in one color and -5 in another color? I am not using  rnacentral.org. Sorry, I'm new to Genoverse.
Thank you

**Comment by AntonPetrov** [comment]
If you are not using rnacentral.org then you might want to raise this issue in https://github.com/wtsi-web/Genoverse as this repo is an adaptation of Genoverse for RNAcentral using AngularJS. The main Genoverse repo will have the latest code and the most up-to-date documentation. Sorry I can't help more!

**Comment by pradyumnasagar** [comment]
Ok Thanks
